export const PLANT_LIST_REQUEST = 'PLANT_LIST_REQUEST';
export const PLANT_LIST_SUCCESS = 'PLANT_LIST_SUCCESS';
export const PLANT_LIST_FAIL = 'PLANT_LIST_FAIL';

export const PLANT_DETAILS_REQUEST = 'PLANT_DETAILS_REQUEST';
export const PLANT_DETAILS_SUCCESS = 'PLANT_DETAILS_SUCCESS';
export const PLANT_DETAILS_FAIL = 'PLANT_DETAILS_FAIL';
