const plants = [
  {
    _id: '1',
    commonName: 'sunflower',
    scientificName: 'helianthus x multiflorus',
    image: ['amy-lynn-grover-aa-IOd1Vop8-unsplash.jpg'],
    colors: ['gold', 'yellow'],
    spacingMinInches: 24,
    spacingMaxInches: 24,
    heightMinInches: 48,
    heightMaxInches: 60,
    bloomMonths: 'Aug - Oct',
    light: 'full sun',
    description:
      'Helianthus x multiflorus are hairy and coarse leaved, clump forming plants with spectacular brilliant yellow flowers that can be quite stunning. The flowers are borne singly on long stiff stalks and can be single, with a domed centre or they can be doubles. The doubles are the most spectacular.',
    url: 'https://en.wikipedia.org/wiki/Digitalis_purpurea',
    rating: 5,
    numReviews: 5,
  },
  {
    _id: '2',
    commonName: 'oriental poppy',
    scientificName: 'papaver orientale',
    image: ['pawel-czerwinski-vtKm2M7hmIg-unsplash.jpg'],
    colors: ['orange', 'red', 'rose', 'scarlet', 'white'],
    spacingMinInches: 12,
    spacingMaxInches: 12,
    heightMinInches: 24,
    heightMaxInches: 36,
    bloomMonths: 'May - Jun',
    light: 'full sun',
    description:
      'Papaver orientale, commonly called Oriental poppy, is among the most popular poppies available. They are clump-forming plants that most often feature flowers in shades of red, orange and pink. Serrate, thistle-like, grayish-green leaves (to 12” long) are pinnately dissected into lance-shaped segments and have a somewhat weedy appearance.',
    url: 'https://en.wikipedia.org/wiki/Digitalis_purpurea',
    rating: 4.5,
    numReviews: 2,
  },
  {
    _id: '3',
    commonName: 'forget-me-not',
    scientificName: 'myosotis l.',
    image: ['pontus-wellgraf-EYx_r0B0oJ4-unsplash.jpg'],
    colors: ['blue'],
    spacingMinInches: 8,
    spacingMaxInches: 10,
    heightMinInches: 7,
    heightMaxInches: 12,
    bloomMonths: 'Apr - May',
    light: 'semi-shade/shade',
    description:
      'Biennial. Myosotis is a genus of flowering plants in the family Boraginaceae. The name comes from the Ancient Greek, which the foliage is thought to resemble. In the northern hemisphere they are colloquially denominated forget-me-nots or scorpion grasses.',
    url: 'https://en.wikipedia.org/wiki/Digitalis_purpurea',
    rating: 4,
    numReviews: 4,
  },
  {
    _id: '4',
    commonName: 'foxglove',
    scientificName: 'digitalis purpurea',
    image: ['slawek-k-qOW5oeANw5E-unsplash-foxglove.jpg'],
    colors: ['pink, purple, rose, white, yellow'],
    spacingMinInches: 18,
    spacingMaxInches: 24,
    heightMinInches: 36,
    heightMaxInches: 60,
    bloomMonths: 'Jun - July',
    light: 'semi-shade/shade',
    description:
      'Biennial. The plant is a popular garden subject, with many cultivars available. It is the original source of the heart medicine digoxin (also called digitalis or digitalin). This biennial plant grows as a rosette of leaves in the first year after sowing, before flowering and then dying in the second year (i.e. it is monocarpic). It generally produces enough seeds, however, so that new plants will continue to grow in a garden setting.',
    url: 'https://en.wikipedia.org/wiki/Digitalis_purpurea',
    rating: 4,
    numReviews: 4,
  },
];

export default plants;
